// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  browser = await chromium.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/orchestration-stage.html?persona=p7&role=player&kind=chromium&slot=6"));
  browser = await chromium.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/orchestration-stage.html?persona=p6&role=player&kind=chromium&slot=5"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/orchestration-stage.html?persona=p3&role=player&kind=webkit&slot=2"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/orchestration-stage.html?persona=p1&role=player&kind=webkit&slot=0"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/orchestration-stage.html?persona=p2&role=player&kind=webkit&slot=1"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/orchestration-stage.html?persona=spectator&role=main-site&kind=webkit&slot=8"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/orchestration-stage.html?persona=ops&role=monitor&kind=webkit&slot=7"));
  browser = await firefox.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/orchestration-stage.html?persona=p4&role=player&kind=firefox&slot=3"));
  browser = await firefox.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/orchestration-stage.html?persona=p5&role=player&kind=firefox&slot=4"));
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
