// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  browser = await chromium.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/canvas.html?role=p6&colour=%231e88e5"));
  browser = await chromium.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/canvas.html?role=spectator&colour=%23999"));
  browser = await chromium.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/canvas.html?role=p7&colour=%238e24aa"));
  browser = await firefox.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/canvas.html?role=p4&colour=%2343a047"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/canvas.html?role=p3&colour=%23fdd835"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/canvas.html?role=operator&colour=%23000"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/canvas.html?role=p1&colour=%23e53935"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/canvas.html?role=p2&colour=%23fb8c00"));
  browser = await firefox.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/canvas.html?role=p5&colour=%2300acc1"));
  await page.waitForSelector("[data-testid=\"tile-0-0\"]");
  await page.waitForSelector("[data-testid=\"tile-0-0\"]");
  await page.waitForSelector("[data-testid=\"tile-0-0\"]");
  await page.waitForSelector("[data-testid=\"tile-0-0\"]");
  await page.waitForSelector("[data-testid=\"tile-0-0\"]");
  await page.waitForSelector("[data-testid=\"tile-0-0\"]");
  await page.waitForSelector("[data-testid=\"tile-0-0\"]");
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-2-2\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-2-2\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-2-2\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-2-2\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-2-2\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-2-2\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-2-2\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-3-5\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-3-5\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-3-5\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-3-5\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-3-5\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-3-5\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-3-5\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-5-7\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-5-7\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-5-7\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-5-7\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-5-7\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-5-7\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-5-7\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-7-3\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-7-3\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-7-3\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-7-3\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-7-3\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-7-3\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-7-3\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-8-8\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-8-8\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-8-8\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-8-8\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-8-8\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-8-8\"]");
  }
  try {
    await page.getByRole("player", { name: "" }).click();
  } catch {
    await page.click("[data-testid=\"tile-8-8\"]");
  }
  await page.evaluate("document.querySelectorAll('.tile[data-claimed]').length");
  await page.evaluate("document.querySelectorAll('.tile[data-claimed]').length");
  await page.evaluate("document.querySelectorAll('.tile[data-claimed]').length");
  await page.evaluate("document.querySelectorAll('.tile[data-claimed]').length");
  await page.evaluate("document.querySelectorAll('.tile[data-claimed]').length");
  await page.evaluate("document.querySelectorAll('.tile[data-claimed]').length");
  await page.evaluate("document.querySelectorAll('.tile[data-claimed]').length");
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
