// Auto-generated by octowright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  browser = await webkit.launch({ headless: false });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:58535/seed/verify-stage.html?persona=vs-arithmetic&role=arithmetic&kind=webkit&slot=2"));
  browser = await webkit.launch({ headless: false });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:58535/seed/verify-stage.html?persona=vs-counter&role=counter&kind=webkit&slot=1"));
  browser = await webkit.launch({ headless: false });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:58535/seed/verify-stage.html?persona=vs-form&role=form&kind=webkit&slot=0"));
  await page.evaluate("document.body.innerHTML = '<input id=user><input id=pass type=password>'");
  try {
    await page.getByRole("form", { name: "" }).fill("cosmo");
  } catch {
    await page.fill("#user", "cosmo");
  }
  try {
    await page.getByRole("form", { name: "" }).fill("<redacted:password>");
  } catch {
    await page.fill("#pass", "<redacted:password>");
  }
  if (!(await page.evaluate("document.querySelector('#user').value"))) throw new Error('JS mismatch');
  if (!(await page.evaluate("document.querySelector('#pass').value"))) throw new Error('JS mismatch');
  await page.evaluate("(() => { document.body.innerHTML = ''; const b = document.createElement('button'); b.id = 'btn'; b.textContent = 'click'; b.dataset.n = '0'; b.addEventListener('click', () => { b.dataset.n = String(parseInt(b.dataset.n) + 1); }); document.body.appendChild(b); })()");
  try {
    await page.getByRole("counter", { name: "click" }).click();
  } catch {
    await page.click("#btn");
  }
  try {
    await page.getByRole("counter", { name: "click" }).click();
  } catch {
    await page.click("#btn");
  }
  try {
    await page.getByRole("counter", { name: "click" }).click();
  } catch {
    await page.click("#btn");
  }
  if (!(await page.evaluate("document.querySelector('#btn').dataset.n"))) throw new Error('JS mismatch');
  if (!(await page.evaluate("2 + 2"))) throw new Error('JS mismatch');
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();

