// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/verify-stage.html?persona=vs-arithmetic&role=arithmetic&kind=webkit&slot=2"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/verify-stage.html?persona=vs-form&role=form&kind=webkit&slot=0"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/verify-stage.html?persona=vs-counter&role=counter&kind=webkit&slot=1"));
  await page.evaluate("document.body.innerHTML = '<input id=user><input id=pass type=password>'");
  try {
    await page.getByRole("form", { name: "" }).fill("alice");
  } catch {
    await page.fill("#user", "alice");
  }
  try {
    await page.getByRole("form", { name: "" }).fill("hunter2");
  } catch {
    await page.fill("#pass", "hunter2");
  }
  await page.evaluate("(() => { document.body.innerHTML = ''; const b = document.createElement('button'); b.id = 'btn'; b.textContent = 'click'; b.dataset.n = '0'; b.addEventListener('click', () => { b.dataset.n = String(parseInt(b.dataset.n) + 1); }); document.body.appendChild(b); })()");
  try {
    await page.getByRole("counter", { name: "click" }).click();
  } catch {
    await page.click("#btn");
  }
  try {
    await page.getByRole("counter", { name: "click" }).click();
  } catch {
    await page.click("#btn");
  }
  try {
    await page.getByRole("counter", { name: "click" }).click();
  } catch {
    await page.click("#btn");
  }
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
