# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path

_SEMANTIC_LOCATOR_KEYS = ("role", "label", "text", "test_id")

_PY_HEADER = '''\
"""Auto-generated by octowright. Replays a recorded MCP session."""
import asyncio
from pathlib import Path
from playwright.async_api import async_playwright


def _resolve_bundle_url(raw: str) -> str:
    if raw.startswith("bundle://"):
        relative = raw.removeprefix("bundle://")
        return (Path(__file__).resolve().parents[1] / relative).resolve().as_uri()
    return raw


async def main() -> None:
    async with async_playwright() as p:
'''

_PY_FOOTER = """\
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
"""

_TS_HEADER = """\
// Auto-generated by octowright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;
"""

_TS_FOOTER = """\
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
"""


def _has_semantic_locator(entry: dict) -> bool:
    return any(entry.get(key) for key in _SEMANTIC_LOCATOR_KEYS)


def _py_locator(entry: dict) -> str | None:
    if entry.get("role"):
        args = [repr(entry["role"])]
        if entry.get("role_name") is not None:
            args.append(f"name={entry['role_name']!r}")
            if entry.get("role_exact"):
                args.append("exact=True")
        return f"page.get_by_role({', '.join(args)})"
    if entry.get("label"):
        return f"page.get_by_label({entry['label']!r})"
    if entry.get("text"):
        return f"page.get_by_text({entry['text']!r})"
    if entry.get("test_id"):
        return f"page.get_by_test_id({entry['test_id']!r})"
    return None


def _ts_locator(entry: dict) -> str | None:
    if entry.get("role"):
        args = [json.dumps(entry["role"])]
        opts: dict[str, object] = {}
        if entry.get("role_name") is not None:
            opts["name"] = entry["role_name"]
            if entry.get("role_exact"):
                opts["exact"] = True
        if opts:
            rendered_opts = ", ".join(f"{key}: {json.dumps(value)}" for key, value in opts.items())
            args.append(f"{{ {rendered_opts} }}")
        return f"page.getByRole({', '.join(args)})"
    if entry.get("label"):
        return f"page.getByLabel({json.dumps(entry['label'])})"
    if entry.get("text"):
        return f"page.getByText({json.dumps(entry['text'])})"
    if entry.get("test_id"):
        return f"page.getByTestId({json.dumps(entry['test_id'])})"
    return None


def _py_semantic_with_fallback(semantic_call: str, fallback_call: str) -> str:
    return f"        try:\n            {semantic_call}\n        except Exception:\n            {fallback_call}"


def _ts_semantic_with_fallback(semantic_call: str, fallback_call: str) -> str:
    return f"  try {{\n    {semantic_call}\n  }} catch {{\n    {fallback_call}\n  }}"


def _launch_viewport(entry: dict) -> dict[str, int]:
    vp = entry.get("viewport")
    if isinstance(vp, dict) and isinstance(vp.get("w"), int) and isinstance(vp.get("h"), int):
        return {"w": vp["w"], "h": vp["h"]}
    return {"w": 1280, "h": 800}


# --- Python emitter: per-action handlers + dispatch table ----------------


def _py_launch(entry: dict) -> str:
    kind = entry["kind"]
    vp = _launch_viewport(entry)
    headed = entry.get("headed", True)
    url = entry["url"]
    user_data_dir = entry.get("user_data_dir")
    if user_data_dir:
        return (
            f"        ctx = await p.{kind}.launch_persistent_context(\n"
            f"            {user_data_dir!r},\n"
            f"            headless={not headed},\n"
            f"            viewport={{'width': {vp['w']}, 'height': {vp['h']}}},\n"
            f"        )\n"
            f"        browser = None\n"
            f"        page = ctx.pages[0] if ctx.pages else await ctx.new_page()\n"
            f"        await page.goto(_resolve_bundle_url({url!r}))"
        )
    return (
        f"        browser = await p.{kind}.launch(headless={not headed})\n"
        f"        ctx = await browser.new_context(viewport={{'width': {vp['w']}, 'height': {vp['h']}}})\n"
        f"        page = await ctx.new_page()\n"
        f"        await page.goto(_resolve_bundle_url({url!r}))"
    )


def _py_click(entry: dict) -> str:
    if _has_semantic_locator(entry):
        loc = _py_locator(entry)
        if loc is not None:
            return _py_semantic_with_fallback(f"await {loc}.click()", f"await page.click({entry['selector']!r})")
    return f"        await page.click({entry['selector']!r})"


def _py_fill(entry: dict) -> str:
    if _has_semantic_locator(entry):
        loc = _py_locator(entry)
        if loc is not None:
            return _py_semantic_with_fallback(
                f"await {loc}.fill({entry['value']!r})",
                f"await page.fill({entry['selector']!r}, {entry['value']!r})",
            )
    return f"        await page.fill({entry['selector']!r}, {entry['value']!r})"


def _py_click_by(entry: dict) -> str | None:
    loc = _py_locator(entry)
    if loc is not None:
        call = f"await {loc}.click()"
        if entry.get("selector"):
            return _py_semantic_with_fallback(call, f"await page.click({entry['selector']!r})")
        return f"        {call}"
    if entry.get("selector"):
        return f"        await page.click({entry['selector']!r})"
    return None


def _py_fill_by(entry: dict) -> str | None:
    loc = _py_locator(entry)
    if loc is not None:
        call = f"await {loc}.fill({entry['value']!r})"
        if entry.get("selector"):
            return _py_semantic_with_fallback(call, f"await page.fill({entry['selector']!r}, {entry['value']!r})")
        return f"        {call}"
    if entry.get("selector"):
        return f"        await page.fill({entry['selector']!r}, {entry['value']!r})"
    return None


def _py_wait_for(entry: dict) -> str:
    if entry.get("selector"):
        return f"        await page.wait_for_selector({entry['selector']!r})"
    if entry.get("text"):
        return (
            f"        await page.wait_for_function("
            f"'t => document.body && document.body.innerText.includes(t)', "
            f"arg={entry['text']!r})"
        )
    return "        await page.wait_for_load_state('networkidle')"


def _py_select_option(entry: dict) -> str:
    sel = entry["selector"]
    if entry.get("value") is not None:
        return f"        await page.select_option({sel!r}, value={entry['value']!r})"
    if entry.get("label") is not None:
        return f"        await page.select_option({sel!r}, label={entry['label']!r})"
    if entry.get("index") is not None:
        return f"        await page.select_option({sel!r}, index={entry['index']!r})"
    return f"        await page.select_option({sel!r})"


_PY_HANDLERS: dict[str, Callable[[dict], str | None]] = {
    "launch": _py_launch,
    "navigate": lambda e: f"        await page.goto(_resolve_bundle_url({e['url']!r}))",
    "click": _py_click,
    "fill": _py_fill,
    "click_by": _py_click_by,
    "fill_by": _py_fill_by,
    "type": lambda e: f"        await page.type({e['selector']!r}, {e['text']!r}, delay={e.get('delay_ms') or 0})",
    "press_key": lambda e: f"        await page.keyboard.press({e['key']!r})",
    "screenshot": lambda e: f"        await page.screenshot(path={e['path']!r})",
    "evaluate": lambda e: f"        await page.evaluate({e['expression']!r})",
    "wait_for": _py_wait_for,
    "hover": lambda e: f"        await page.hover({e['selector']!r})",
    "select_option": _py_select_option,
    "drag": lambda e: f"        await page.drag_and_drop({e['source']!r}, {e['target']!r})",
    "navigate_back": lambda _e: "        await page.go_back()",
    "resize": lambda e: f"        await page.set_viewport_size({{'width': {e['width']}, 'height': {e['height']}}})",
}


def _py_line(entry: dict) -> str | None:
    handler = _PY_HANDLERS.get(entry.get("action") or "")
    return handler(entry) if handler else None


# --- TypeScript emitter: per-action handlers + dispatch table ------------


def _ts_launch(entry: dict) -> str:
    kind = entry["kind"]
    vp = _launch_viewport(entry)
    headed = entry.get("headed", True)
    url = entry["url"]
    user_data_dir = entry.get("user_data_dir")
    if user_data_dir:
        return (
            f"  ctx = await {kind}.launchPersistentContext({json.dumps(user_data_dir)}, {{\n"
            f"    headless: {str(not headed).lower()},\n"
            f"    viewport: {{ width: {vp['w']}, height: {vp['h']} }},\n"
            f"  }});\n"
            f"  page = ctx.pages()[0] ?? await ctx.newPage();\n"
            f"  await page.goto(resolveBundleUrl({json.dumps(url)}));"
        )
    return (
        f"  browser = await {kind}.launch({{ headless: {str(not headed).lower()} }});\n"
        f"  ctx = await browser.newContext({{ viewport: {{ width: {vp['w']}, height: {vp['h']} }} }});\n"
        f"  page = await ctx.newPage();\n"
        f"  await page.goto(resolveBundleUrl({json.dumps(url)}));"
    )


def _ts_click(entry: dict) -> str:
    if _has_semantic_locator(entry):
        loc = _ts_locator(entry)
        if loc is not None:
            return _ts_semantic_with_fallback(
                f"await {loc}.click();", f"await page.click({json.dumps(entry['selector'])});"
            )
    return f"  await page.click({json.dumps(entry['selector'])});"


def _ts_fill(entry: dict) -> str:
    if _has_semantic_locator(entry):
        loc = _ts_locator(entry)
        if loc is not None:
            return _ts_semantic_with_fallback(
                f"await {loc}.fill({json.dumps(entry['value'])});",
                f"await page.fill({json.dumps(entry['selector'])}, {json.dumps(entry['value'])});",
            )
    return f"  await page.fill({json.dumps(entry['selector'])}, {json.dumps(entry['value'])});"


def _ts_click_by(entry: dict) -> str | None:
    loc = _ts_locator(entry)
    if loc is not None:
        call = f"await {loc}.click();"
        if entry.get("selector"):
            return _ts_semantic_with_fallback(call, f"await page.click({json.dumps(entry['selector'])});")
        return f"  {call}"
    if entry.get("selector"):
        return f"  await page.click({json.dumps(entry['selector'])});"
    return None


def _ts_fill_by(entry: dict) -> str | None:
    loc = _ts_locator(entry)
    if loc is not None:
        call = f"await {loc}.fill({json.dumps(entry['value'])});"
        if entry.get("selector"):
            return _ts_semantic_with_fallback(
                call, f"await page.fill({json.dumps(entry['selector'])}, {json.dumps(entry['value'])});"
            )
        return f"  {call}"
    if entry.get("selector"):
        return f"  await page.fill({json.dumps(entry['selector'])}, {json.dumps(entry['value'])});"
    return None


def _ts_wait_for(entry: dict) -> str:
    if entry.get("selector"):
        return f"  await page.waitForSelector({json.dumps(entry['selector'])});"
    if entry.get("text"):
        return (
            f"  await page.waitForFunction("
            f"(t) => document.body && document.body.innerText.includes(t), "
            f"{json.dumps(entry['text'])});"
        )
    return "  await page.waitForLoadState('networkidle');"


def _ts_select_option(entry: dict) -> str:
    sel = json.dumps(entry["selector"])
    if entry.get("value") is not None:
        return f"  await page.selectOption({sel}, {{ value: {json.dumps(entry['value'])} }});"
    if entry.get("label") is not None:
        return f"  await page.selectOption({sel}, {{ label: {json.dumps(entry['label'])} }});"
    if entry.get("index") is not None:
        return f"  await page.selectOption({sel}, {{ index: {entry['index']} }});"
    return f"  await page.selectOption({sel});"


_TS_HANDLERS: dict[str, Callable[[dict], str | None]] = {
    "launch": _ts_launch,
    "navigate": lambda e: f"  await page.goto(resolveBundleUrl({json.dumps(e['url'])}));",
    "click": _ts_click,
    "fill": _ts_fill,
    "click_by": _ts_click_by,
    "fill_by": _ts_fill_by,
    "type": (
        lambda e: (
            f"  await page.type({json.dumps(e['selector'])}, {json.dumps(e['text'])}, "
            f"{{ delay: {e.get('delay_ms') or 0} }});"
        )
    ),
    "press_key": lambda e: f"  await page.keyboard.press({json.dumps(e['key'])});",
    "screenshot": lambda e: f"  await page.screenshot({{ path: {json.dumps(e['path'])} }});",
    "evaluate": lambda e: f"  await page.evaluate({json.dumps(e['expression'])});",
    "wait_for": _ts_wait_for,
    "hover": lambda e: f"  await page.hover({json.dumps(e['selector'])});",
    "select_option": _ts_select_option,
    "drag": lambda e: f"  await page.dragAndDrop({json.dumps(e['source'])}, {json.dumps(e['target'])});",
    "navigate_back": lambda _e: "  await page.goBack();",
    "resize": lambda e: f"  await page.setViewportSize({{ width: {e['width']}, height: {e['height']} }});",
}


def _ts_line(entry: dict) -> str | None:
    handler = _TS_HANDLERS.get(entry.get("action") or "")
    return handler(entry) if handler else None


def export_script(log_path: Path, out_path: Path, fmt: str = "python") -> Path:
    if fmt not in ("python", "ts"):
        raise ValueError(f"fmt must be 'python' or 'ts', got {fmt!r}")

    header, footer, line_fn = _renderer(fmt)
    lines: list[str] = [header]
    with log_path.open("r", encoding="utf-8") as fh:
        for raw in fh:
            raw = raw.strip()
            if not raw:
                continue
            entry = json.loads(raw)
            rendered = line_fn(entry)
            if rendered is not None:
                lines.append(rendered)
    lines.append(footer)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


def _renderer(fmt: str) -> tuple[str, str, Callable[[dict], str | None]]:
    if fmt == "python":
        return _PY_HEADER, _PY_FOOTER, _py_line
    return _TS_HEADER, _TS_FOOTER, _ts_line
