# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path

from octowright._export_shared import (
    _has_semantic_locator,
    _launch_viewport,
    _safe_int,
    _validate_dialog_policy,
    _validate_kind,
)
from octowright._paths import atomic_write_text
from octowright.macros.storage import load_macro

_PY_HEADER = '''\
"""Auto-generated by octowright. Replays a recorded MCP session."""
import asyncio
from pathlib import Path
from playwright.async_api import async_playwright


def _resolve_bundle_url(raw: str) -> str:
    if raw.startswith("bundle://"):
        relative = raw.removeprefix("bundle://")
        return (Path(__file__).resolve().parents[1] / relative).resolve().as_uri()
    return raw


async def main() -> None:
    async with async_playwright() as p:
'''

_PY_FOOTER = """\
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
"""


def _py_locator(entry: dict) -> str | None:
    if entry.get("role"):
        args = [repr(entry["role"])]
        if entry.get("role_name") is not None:
            args.append(f"name={entry['role_name']!r}")
            if entry.get("role_exact"):
                args.append("exact=True")
        return f"page.get_by_role({', '.join(args)})"
    if entry.get("label"):
        return f"page.get_by_label({entry['label']!r})"
    if entry.get("text"):
        return f"page.get_by_text({entry['text']!r})"
    if entry.get("test_id"):
        return f"page.get_by_test_id({entry['test_id']!r})"
    return None


def _py_semantic_with_fallback(semantic_call: str, fallback_call: str) -> str:
    return f"        try:\n            {semantic_call}\n        except Exception:\n            {fallback_call}"


# --- Python emitter: per-action handlers + dispatch table ----------------


def _py_launch(entry: dict) -> str:
    kind = _validate_kind(entry["kind"], action="launch")
    vp = _launch_viewport(entry)
    headed = entry.get("headed", True)
    url = entry["url"]
    user_data_dir = entry.get("user_data_dir")
    if user_data_dir:
        return (
            f"        _kind = {kind!r}\n"
            f"        ctx = await getattr(p, _kind).launch_persistent_context(\n"
            f"            {user_data_dir!r},\n"
            f"            headless={not headed},\n"
            f"            viewport={{'width': {vp['w']}, 'height': {vp['h']}}},\n"
            f"        )\n"
            f"        browser = None\n"
            f"        page = ctx.pages[0] if ctx.pages else await ctx.new_page()\n"
            f"        await page.goto(_resolve_bundle_url({url!r}))"
        )
    return (
        f"        _kind = {kind!r}\n"
        f"        browser = await getattr(p, _kind).launch(headless={not headed})\n"
        f"        ctx = await browser.new_context(viewport={{'width': {vp['w']}, 'height': {vp['h']}}})\n"
        f"        page = await ctx.new_page()\n"
        f"        await page.goto(_resolve_bundle_url({url!r}))"
    )


def _py_click(entry: dict) -> str:
    if _has_semantic_locator(entry):
        loc = _py_locator(entry)
        if loc is not None:
            return _py_semantic_with_fallback(f"await {loc}.click()", f"await page.click({entry['selector']!r})")
    return f"        await page.click({entry['selector']!r})"


def _py_fill(entry: dict) -> str:
    if _has_semantic_locator(entry):
        loc = _py_locator(entry)
        if loc is not None:
            return _py_semantic_with_fallback(
                f"await {loc}.fill({entry['value']!r})",
                f"await page.fill({entry['selector']!r}, {entry['value']!r})",
            )
    return f"        await page.fill({entry['selector']!r}, {entry['value']!r})"


def _py_click_by(entry: dict) -> str | None:
    loc = _py_locator(entry)
    if loc is not None:
        call = f"await {loc}.click()"
        if entry.get("selector"):
            return _py_semantic_with_fallback(call, f"await page.click({entry['selector']!r})")
        return f"        {call}"
    if entry.get("selector"):
        return f"        await page.click({entry['selector']!r})"
    return None


def _py_fill_by(entry: dict) -> str | None:
    loc = _py_locator(entry)
    if loc is not None:
        call = f"await {loc}.fill({entry['value']!r})"
        if entry.get("selector"):
            return _py_semantic_with_fallback(call, f"await page.fill({entry['selector']!r}, {entry['value']!r})")
        return f"        {call}"
    if entry.get("selector"):
        return f"        await page.fill({entry['selector']!r}, {entry['value']!r})"
    return None


def _py_wait_for(entry: dict) -> str:
    if entry.get("selector"):
        return f"        await page.wait_for_selector({entry['selector']!r})"
    if entry.get("text"):
        return (
            f"        await page.wait_for_function("
            f"'t => document.body && document.body.innerText.includes(t)', "
            f"arg={entry['text']!r})"
        )
    return "        await page.wait_for_load_state('networkidle')"


def _py_select_option(entry: dict) -> str:
    sel = entry["selector"]
    if entry.get("value") is not None:
        return f"        await page.select_option({sel!r}, value={entry['value']!r})"
    if entry.get("label") is not None:
        return f"        await page.select_option({sel!r}, label={entry['label']!r})"
    if entry.get("index") is not None:
        return f"        await page.select_option({sel!r}, index={entry['index']!r})"
    return f"        await page.select_option({sel!r})"


def _py_cond_while(e: dict) -> str | None:
    c = ""
    if e.get("selector"):
        c = f"await page.locator({e['selector']!r}).count() > 0"
    elif e.get("expression"):
        c = f"await page.evaluate({e['expression']!r})"
    elif e.get("text"):
        c = f"{e['text']!r} in await page.locator('body').inner_text()"
    if not c:
        return None
    a = e["action"]
    p = "if " if a in ("if", "if_not") else "while "
    if a in ("if_not", "while_not"):
        c = f"not ({c})"
    return f"        {p}{c}:"


def _py_set_dialog_policy(entry: dict) -> str:
    policy = _validate_dialog_policy(entry.get("policy"))
    if policy == "manual":
        # "manual" means the recording session didn't auto-handle dialogs;
        # replay shouldn't either. Also fixes a pre-existing functional bug:
        # Dialog has no .manual() method, so the old unconditional splice
        # would have generated code that raised AttributeError at runtime.
        return "        # set_dialog_policy: manual (no auto-handler recorded)"
    # `policy` is embedded as a lambda default-arg (a repr'd string literal,
    # i.e. DATA) and resolved via getattr at call time, never spliced as a
    # bare identifier. The default-arg (vs. a shared outer variable) also
    # avoids Python's late-binding closure trap if multiple set_dialog_policy
    # actions appear in one recording.
    return (
        f"        page.on('dialog', lambda dialog, _policy={policy!r}: asyncio.create_task(getattr(dialog, _policy)()))"
    )


_PY_HANDLERS: dict[str, Callable[[dict], str | None]] = {
    "launch": _py_launch,
    "navigate": lambda e: f"        await page.goto(_resolve_bundle_url({e['url']!r}))",
    "click": _py_click,
    "fill": _py_fill,
    "click_by": _py_click_by,
    "fill_by": _py_fill_by,
    "type": lambda e: (
        f"        await page.type({e['selector']!r}, {e['text']!r}, "
        f"delay={_safe_int(e.get('delay_ms'), action='type', field='delay_ms', default=0)})"
    ),
    "press_key": lambda e: f"        await page.keyboard.press({e['key']!r})",
    "screenshot": lambda e: f"        await page.screenshot(path={e['path']!r})",
    "evaluate": lambda e: f"        await page.evaluate({e['expression']!r})",
    "wait_for": _py_wait_for,
    "hover": lambda e: f"        await page.hover({e['selector']!r})",
    "select_option": _py_select_option,
    "drag": lambda e: f"        await page.drag_and_drop({e['source']!r}, {e['target']!r})",
    "navigate_back": lambda _e: "        await page.go_back()",
    "resize": lambda e: (
        f"        await page.set_viewport_size({{'width': "
        f"{_safe_int(e['width'], action='resize', field='width')}, 'height': "
        f"{_safe_int(e['height'], action='resize', field='height')}}})"
    ),
    "expect_url": lambda e: (
        f"        if not __import__('re').search({e['pattern']!r}, page.url): raise RuntimeError('URL mismatch')"
        if e.get("mode", "regex") == "regex"
        else (
            f"        if page.url != {e['pattern']!r}: raise RuntimeError('URL mismatch')"
            if e.get("mode") == "equals"
            else f"        if {e['pattern']!r} not in page.url: raise RuntimeError('URL mismatch')"
        )
    ),
    "expect_text": lambda e: (
        f"        if {e['text']!r} not in await page.locator({e['selector']!r}).inner_text(): raise RuntimeError('Text mismatch')"
    ),
    "expect_selector": lambda e: (
        f"        if await page.locator({e['selector']!r}).count() == 0: raise RuntimeError('Selector mismatch')"
    ),
    "expect_js": lambda e: (
        f"        if not await page.evaluate({e['expression']!r}): raise RuntimeError('JS mismatch')"
    ),
    "open_url": lambda e: f"        page = await ctx.new_page()\n        await page.goto({e['url']!r})",
    "switch_page": lambda e: f"        page = ctx.pages[{_safe_int(e['index'], action='switch_page', field='index')}]",
    "close_page": lambda _e: "        await page.close()",
    "reset_frame": lambda _e: "        pass",
    "mock_route": lambda e: (
        f"        await page.route({e['url_pattern']!r}, lambda route: route.fulfill("
        f"status={_safe_int(e.get('status'), action='mock_route', field='status', default=200)}, "
        f"body={e.get('body', '')!r}))"
    ),
    "unmock_route": lambda e: f"        await page.unroute({e['url_pattern']!r})",
    "set_dialog_policy": _py_set_dialog_policy,
    "set_input_files": lambda e: f"        await page.set_input_files({e['selector']!r}, {e.get('files', [])!r})",
    "if": _py_cond_while,
    "if_not": _py_cond_while,
    "while": _py_cond_while,
    "while_not": _py_cond_while,
}


def _py_line(entry: dict) -> str | None:
    handler = _PY_HANDLERS.get(entry.get("action") or "")
    return handler(entry) if handler else None


def export_script(log_path: Path, out_path: Path, fmt: str = "python", manifest: dict | None = None) -> Path:

    if fmt not in ("python", "ts"):
        raise ValueError(f"fmt must be 'python' or 'ts', got {fmt!r}")

    header, footer, line_fn = _renderer(fmt)
    lines: list[str] = [header]

    def process_entries(entries: list[dict], current_indent: int) -> int:
        for entry in entries:
            action = entry.get("action")
            if not action:
                continue

            if action == "macro_call":
                name = entry.get("name")
                if name:
                    try:
                        macro = load_macro(name)
                        current_indent = process_entries(macro.get("actions", []), current_indent)
                    except Exception:
                        pass
                continue

            if action == "end_block":
                current_indent = max(0, current_indent - 1)
                if fmt == "ts":
                    lines.append(("  " * (1 + current_indent)) + "}")
                continue

            rendered = line_fn(entry)
            if rendered is not None:
                base = "        " if fmt == "python" else "  "
                extra = "    " * current_indent if fmt == "python" else "  " * current_indent

                indented_lines = []
                for line in rendered.split("\n"):
                    if line.startswith(base):
                        indented_lines.append(base + extra + line[len(base) :])
                    else:
                        indented_lines.append(line)
                lines.append("\n".join(indented_lines))

            if action in ("if", "if_not", "while", "while_not"):
                current_indent += 1
        return current_indent

    with log_path.open("r", encoding="utf-8") as fh:
        raw_entries = [json.loads(line) for line in fh if line.strip()]
        process_entries(raw_entries, 0)

    lines.append(footer)

    if manifest and "critical_points" in manifest:
        lines.append("")
        comment_prefix = "#" if fmt == "python" else "//"
        lines.append(f"{comment_prefix} Critical Points:")
        for cp in manifest["critical_points"]:
            lines.append(f"{comment_prefix} - {cp}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(out_path, "\n".join(lines) + "\n")
    return out_path


def _renderer(fmt: str) -> tuple[str, str, Callable[[dict], str | None]]:
    if fmt == "python":
        return _PY_HEADER, _PY_FOOTER, _py_line
    from octowright.export_ts import _TS_FOOTER, _TS_HEADER, _ts_line

    return _TS_HEADER, _TS_FOOTER, _ts_line
