# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""TypeScript replay-script emitter, split out of ``export.py`` to keep that
module under the repository's LOC ceiling. Mirrors the Python emitter
action-for-action; see ``export.py`` for the shared entry point
(``export_script``) that dispatches to whichever emitter matches ``fmt``."""

from __future__ import annotations

import json
from collections.abc import Callable

from octowright._export_shared import (
    _has_semantic_locator,
    _launch_viewport,
    _safe_int,
    _validate_dialog_policy,
    _validate_kind,
)

_TS_HEADER = """\
// Auto-generated by octowright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;
"""

_TS_FOOTER = """\
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
"""


def _ts_locator(entry: dict) -> str | None:
    if entry.get("role"):
        args = [json.dumps(entry["role"])]
        opts: dict[str, object] = {}
        if entry.get("role_name") is not None:
            opts["name"] = entry["role_name"]
            if entry.get("role_exact"):
                opts["exact"] = True
        if opts:
            rendered_opts = ", ".join(f"{key}: {json.dumps(value)}" for key, value in opts.items())
            args.append(f"{{ {rendered_opts} }}")
        return f"page.getByRole({', '.join(args)})"
    if entry.get("label"):
        return f"page.getByLabel({json.dumps(entry['label'])})"
    if entry.get("text"):
        return f"page.getByText({json.dumps(entry['text'])})"
    if entry.get("test_id"):
        return f"page.getByTestId({json.dumps(entry['test_id'])})"
    return None


def _ts_semantic_with_fallback(semantic_call: str, fallback_call: str) -> str:
    return f"  try {{\n    {semantic_call}\n  }} catch {{\n    {fallback_call}\n  }}"


def _ts_cond_while(e: dict) -> str | None:
    c = ""
    if e.get("selector"):
        c = f"await page.locator({json.dumps(e['selector'])}).count() > 0"
    elif e.get("expression"):
        c = f"await page.evaluate({json.dumps(e['expression'])})"
    elif e.get("text"):
        c = f"(await page.locator('body').innerText()).includes({json.dumps(e['text'])})"
    if not c:
        return None
    a = e["action"]
    p = "if " if a in ("if", "if_not") else "while "
    if a in ("if_not", "while_not"):
        c = f"!({c})"
    return f"  {p}({c}) {{"


def _ts_launch(entry: dict) -> str:
    kind = _validate_kind(entry["kind"], action="launch")
    vp = _launch_viewport(entry)
    headed = entry.get("headed", True)
    url = entry["url"]
    user_data_dir = entry.get("user_data_dir")
    # `kind` is embedded as a JSON string literal (DATA) and resolved via a
    # runtime object-index lookup, never spliced as a bare identifier.
    kind_lookup = (
        f"  const kind = {json.dumps(kind)};\n  const engine = ({{ chromium, firefox, webkit }} as any)[kind];\n"
    )
    if user_data_dir:
        return (
            f"{kind_lookup}"
            f"  ctx = await engine.launchPersistentContext({json.dumps(user_data_dir)}, {{\n"
            f"    headless: {str(not headed).lower()},\n"
            f"    viewport: {{ width: {vp['w']}, height: {vp['h']} }},\n"
            f"  }});\n"
            f"  page = ctx.pages()[0] ?? await ctx.newPage();\n"
            f"  await page.goto(resolveBundleUrl({json.dumps(url)}));"
        )
    return (
        f"{kind_lookup}"
        f"  browser = await engine.launch({{ headless: {str(not headed).lower()} }});\n"
        f"  ctx = await browser.newContext({{ viewport: {{ width: {vp['w']}, height: {vp['h']} }} }});\n"
        f"  page = await ctx.newPage();\n"
        f"  await page.goto(resolveBundleUrl({json.dumps(url)}));"
    )


def _ts_click(entry: dict) -> str:
    if _has_semantic_locator(entry):
        loc = _ts_locator(entry)
        if loc is not None:
            return _ts_semantic_with_fallback(
                f"await {loc}.click();", f"await page.click({json.dumps(entry['selector'])});"
            )
    return f"  await page.click({json.dumps(entry['selector'])});"


def _ts_fill(entry: dict) -> str:
    if _has_semantic_locator(entry):
        loc = _ts_locator(entry)
        if loc is not None:
            return _ts_semantic_with_fallback(
                f"await {loc}.fill({json.dumps(entry['value'])});",
                f"await page.fill({json.dumps(entry['selector'])}, {json.dumps(entry['value'])});",
            )
    return f"  await page.fill({json.dumps(entry['selector'])}, {json.dumps(entry['value'])});"


def _ts_click_by(entry: dict) -> str | None:
    loc = _ts_locator(entry)
    if loc is not None:
        call = f"await {loc}.click();"
        if entry.get("selector"):
            return _ts_semantic_with_fallback(call, f"await page.click({json.dumps(entry['selector'])});")
        return f"  {call}"
    if entry.get("selector"):
        return f"  await page.click({json.dumps(entry['selector'])});"
    return None


def _ts_fill_by(entry: dict) -> str | None:
    loc = _ts_locator(entry)
    if loc is not None:
        call = f"await {loc}.fill({json.dumps(entry['value'])});"
        if entry.get("selector"):
            return _ts_semantic_with_fallback(
                call, f"await page.fill({json.dumps(entry['selector'])}, {json.dumps(entry['value'])});"
            )
        return f"  {call}"
    if entry.get("selector"):
        return f"  await page.fill({json.dumps(entry['selector'])}, {json.dumps(entry['value'])});"
    return None


def _ts_wait_for(entry: dict) -> str:
    if entry.get("selector"):
        return f"  await page.waitForSelector({json.dumps(entry['selector'])});"
    if entry.get("text"):
        return (
            f"  await page.waitForFunction("
            f"(t) => document.body && document.body.innerText.includes(t), "
            f"{json.dumps(entry['text'])});"
        )
    return "  await page.waitForLoadState('networkidle');"


def _ts_select_option(entry: dict) -> str:
    sel = json.dumps(entry["selector"])
    if entry.get("value") is not None:
        return f"  await page.selectOption({sel}, {{ value: {json.dumps(entry['value'])} }});"
    if entry.get("label") is not None:
        return f"  await page.selectOption({sel}, {{ label: {json.dumps(entry['label'])} }});"
    if entry.get("index") is not None:
        return f"  await page.selectOption({sel}, {{ index: {entry['index']} }});"
    return f"  await page.selectOption({sel});"


def _ts_set_dialog_policy(entry: dict) -> str:
    policy = _validate_dialog_policy(entry.get("policy"))
    if policy == "manual":
        return "  // set_dialog_policy: manual (no auto-handler recorded)"
    # `policy` is embedded as a JSON string literal (DATA) and resolved via a
    # runtime object-index lookup, never spliced as a bare identifier.
    return f"  page.on('dialog', dialog => (dialog as any)[{json.dumps(policy)}]());"


_TS_HANDLERS: dict[str, Callable[[dict], str | None]] = {
    "launch": _ts_launch,
    "navigate": lambda e: f"  await page.goto(resolveBundleUrl({json.dumps(e['url'])}));",
    "click": _ts_click,
    "fill": _ts_fill,
    "click_by": _ts_click_by,
    "fill_by": _ts_fill_by,
    "type": (
        lambda e: (
            f"  await page.type({json.dumps(e['selector'])}, {json.dumps(e['text'])}, "
            f"{{ delay: {_safe_int(e.get('delay_ms'), action='type', field='delay_ms', default=0)} }});"
        )
    ),
    "press_key": lambda e: f"  await page.keyboard.press({json.dumps(e['key'])});",
    "screenshot": lambda e: f"  await page.screenshot({{ path: {json.dumps(e['path'])} }});",
    "evaluate": lambda e: f"  await page.evaluate({json.dumps(e['expression'])});",
    "wait_for": _ts_wait_for,
    "hover": lambda e: f"  await page.hover({json.dumps(e['selector'])});",
    "select_option": _ts_select_option,
    "drag": lambda e: f"  await page.dragAndDrop({json.dumps(e['source'])}, {json.dumps(e['target'])});",
    "navigate_back": lambda _e: "  await page.goBack();",
    "resize": lambda e: (
        f"  await page.setViewportSize({{ width: "
        f"{_safe_int(e['width'], action='resize', field='width')}, height: "
        f"{_safe_int(e['height'], action='resize', field='height')} }});"
    ),
    "expect_url": lambda e: (
        f"  if (!new RegExp({json.dumps(e['pattern'])}).test(page.url())) throw new Error('URL mismatch');"
        if e.get("mode", "regex") == "regex"
        else (
            f"  if (page.url() !== {json.dumps(e['pattern'])}) throw new Error('URL mismatch');"
            if e.get("mode") == "equals"
            else f"  if (!page.url().includes({json.dumps(e['pattern'])})) throw new Error('URL mismatch');"
        )
    ),
    "expect_text": lambda e: (
        f"  if (!(await page.locator({json.dumps(e['selector'])}).innerText()).includes({json.dumps(e['text'])})) throw new Error('Text mismatch');"
    ),
    "expect_selector": lambda e: (
        f"  if (await page.locator({json.dumps(e['selector'])}).count() === 0) throw new Error('Selector mismatch');"
    ),
    "expect_js": lambda e: (
        f"  if (!(await page.evaluate({json.dumps(e['expression'])}))) throw new Error('JS mismatch');"
    ),
    "open_url": lambda e: f"  page = await ctx.newPage();\n  await page.goto({json.dumps(e['url'])});",
    "switch_page": lambda e: f"  page = ctx.pages()[{_safe_int(e['index'], action='switch_page', field='index')}];",
    "close_page": lambda _e: "  await page.close();",
    "reset_frame": lambda _e: "  // reset_frame",
    "mock_route": lambda e: (
        f"  await page.route({json.dumps(e['url_pattern'])}, route => route.fulfill({{ "
        f"status: {_safe_int(e.get('status'), action='mock_route', field='status', default=200)}, "
        f"body: {json.dumps(e.get('body', ''))} }}));"
    ),
    "unmock_route": lambda e: f"  await page.unroute({json.dumps(e['url_pattern'])});",
    "set_dialog_policy": _ts_set_dialog_policy,
    "set_input_files": lambda e: (
        f"  await page.setInputFiles({json.dumps(e['selector'])}, {json.dumps(e.get('files', []))});"
    ),
    "if": _ts_cond_while,
    "if_not": _ts_cond_while,
    "while": _ts_cond_while,
    "while_not": _ts_cond_while,
}


def _ts_line(entry: dict) -> str | None:
    handler = _TS_HANDLERS.get(entry.get("action") or "")
    return handler(entry) if handler else None
