# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path

_PY_HEADER = '''\
"""Auto-generated by mcp-multi-playwright. Replays a recorded MCP session."""
import asyncio
from playwright.async_api import async_playwright


async def main() -> None:
    async with async_playwright() as p:
'''

_PY_FOOTER = """\
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
"""

_TS_HEADER = """\
// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;
"""

_TS_FOOTER = """\
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
"""


def _py_line(entry: dict) -> str | None:
    action = entry.get("action")
    if action == "launch":
        kind = entry["kind"]
        vp = entry.get("viewport") or {"w": 1280, "h": 800}
        headed = entry.get("headed", True)
        url = entry["url"]
        user_data_dir = entry.get("user_data_dir")
        if user_data_dir:
            return (
                f"        ctx = await p.{kind}.launch_persistent_context(\n"
                f"            {user_data_dir!r},\n"
                f"            headless={not headed},\n"
                f"            viewport={{'width': {vp['w']}, 'height': {vp['h']}}},\n"
                f"        )\n"
                f"        browser = None\n"
                f"        page = ctx.pages[0] if ctx.pages else await ctx.new_page()\n"
                f"        await page.goto({url!r})"
            )
        return (
            f"        browser = await p.{kind}.launch(headless={not headed})\n"
            f"        ctx = await browser.new_context(viewport={{'width': {vp['w']}, 'height': {vp['h']}}})\n"
            f"        page = await ctx.new_page()\n"
            f"        await page.goto({url!r})"
        )
    if action == "navigate":
        return f"        await page.goto({entry['url']!r})"
    if action == "click":
        return f"        await page.click({entry['selector']!r})"
    if action == "fill":
        return f"        await page.fill({entry['selector']!r}, {entry['value']!r})"
    if action == "type":
        delay = entry.get("delay_ms") or 0
        return f"        await page.type({entry['selector']!r}, {entry['text']!r}, delay={delay})"
    if action == "press_key":
        return f"        await page.keyboard.press({entry['key']!r})"
    if action == "screenshot":
        return f"        await page.screenshot(path={entry['path']!r})"
    if action == "evaluate":
        return f"        await page.evaluate({entry['expression']!r})"
    if action == "wait_for":
        if entry.get("selector"):
            return f"        await page.wait_for_selector({entry['selector']!r})"
        if entry.get("text"):
            text = entry["text"]
            return (
                f"        await page.wait_for_function("
                f"'t => document.body && document.body.innerText.includes(t)', arg={text!r})"
            )
        return "        await page.wait_for_load_state('networkidle')"
    if action == "hover":
        return f"        await page.hover({entry['selector']!r})"
    if action == "select_option":
        sel = entry["selector"]
        if entry.get("value") is not None:
            return f"        await page.select_option({sel!r}, value={entry['value']!r})"
        if entry.get("label") is not None:
            return f"        await page.select_option({sel!r}, label={entry['label']!r})"
        if entry.get("index") is not None:
            return f"        await page.select_option({sel!r}, index={entry['index']!r})"
        return f"        await page.select_option({sel!r})"
    if action == "drag":
        return f"        await page.drag_and_drop({entry['source']!r}, {entry['target']!r})"
    if action == "navigate_back":
        return "        await page.go_back()"
    if action == "resize":
        return f"        await page.set_viewport_size({{'width': {entry['width']}, 'height': {entry['height']}}})"
    return None


def _ts_line(entry: dict) -> str | None:
    action = entry.get("action")
    if action == "launch":
        kind = entry["kind"]
        vp = entry.get("viewport") or {"w": 1280, "h": 800}
        headed = entry.get("headed", True)
        url = entry["url"]
        user_data_dir = entry.get("user_data_dir")
        if user_data_dir:
            return (
                f"  ctx = await {kind}.launchPersistentContext({json.dumps(user_data_dir)}, {{\n"
                f"    headless: {str(not headed).lower()},\n"
                f"    viewport: {{ width: {vp['w']}, height: {vp['h']} }},\n"
                f"  }});\n"
                f"  page = ctx.pages()[0] ?? await ctx.newPage();\n"
                f"  await page.goto({json.dumps(url)});"
            )
        return (
            f"  browser = await {kind}.launch({{ headless: {str(not headed).lower()} }});\n"
            f"  ctx = await browser.newContext({{ viewport: {{ width: {vp['w']}, height: {vp['h']} }} }});\n"
            f"  page = await ctx.newPage();\n"
            f"  await page.goto({json.dumps(url)});"
        )
    if action == "navigate":
        return f"  await page.goto({json.dumps(entry['url'])});"
    if action == "click":
        return f"  await page.click({json.dumps(entry['selector'])});"
    if action == "fill":
        return f"  await page.fill({json.dumps(entry['selector'])}, {json.dumps(entry['value'])});"
    if action == "type":
        delay = entry.get("delay_ms") or 0
        return f"  await page.type({json.dumps(entry['selector'])}, {json.dumps(entry['text'])}, {{ delay: {delay} }});"
    if action == "press_key":
        return f"  await page.keyboard.press({json.dumps(entry['key'])});"
    if action == "screenshot":
        return f"  await page.screenshot({{ path: {json.dumps(entry['path'])} }});"
    if action == "evaluate":
        return f"  await page.evaluate({json.dumps(entry['expression'])});"
    if action == "wait_for":
        if entry.get("selector"):
            return f"  await page.waitForSelector({json.dumps(entry['selector'])});"
        if entry.get("text"):
            return (
                f"  await page.waitForFunction("
                f"(t) => document.body && document.body.innerText.includes(t), "
                f"{json.dumps(entry['text'])});"
            )
        return "  await page.waitForLoadState('networkidle');"
    if action == "hover":
        return f"  await page.hover({json.dumps(entry['selector'])});"
    if action == "select_option":
        sel = json.dumps(entry["selector"])
        if entry.get("value") is not None:
            return f"  await page.selectOption({sel}, {{ value: {json.dumps(entry['value'])} }});"
        if entry.get("label") is not None:
            return f"  await page.selectOption({sel}, {{ label: {json.dumps(entry['label'])} }});"
        if entry.get("index") is not None:
            return f"  await page.selectOption({sel}, {{ index: {entry['index']} }});"
        return f"  await page.selectOption({sel});"
    if action == "drag":
        return f"  await page.dragAndDrop({json.dumps(entry['source'])}, {json.dumps(entry['target'])});"
    if action == "navigate_back":
        return "  await page.goBack();"
    if action == "resize":
        return f"  await page.setViewportSize({{ width: {entry['width']}, height: {entry['height']} }});"
    return None


def export_script(log_path: Path, out_path: Path, fmt: str = "python") -> Path:
    if fmt not in ("python", "ts"):
        raise ValueError(f"fmt must be 'python' or 'ts', got {fmt!r}")

    header, footer, line_fn = _renderer(fmt)
    lines: list[str] = [header]
    with log_path.open("r", encoding="utf-8") as fh:
        for raw in fh:
            raw = raw.strip()
            if not raw:
                continue
            entry = json.loads(raw)
            rendered = line_fn(entry)
            if rendered is not None:
                lines.append(rendered)
    lines.append(footer)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


def _renderer(fmt: str) -> tuple[str, str, Callable[[dict], str | None]]:
    if fmt == "python":
        return _PY_HEADER, _PY_FOOTER, _py_line
    return _TS_HEADER, _TS_FOOTER, _ts_line
