# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""Auto-generated by octowright. Replays a recorded MCP session."""

import asyncio
from pathlib import Path

from playwright.async_api import async_playwright


def _resolve_bundle_url(raw: str) -> str:
    if raw.startswith("bundle://"):
        relative = raw.removeprefix("bundle://")
        return (Path(__file__).resolve().parents[1] / relative).resolve().as_uri()
    return raw


async def main() -> None:
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1920, "height": 1080})
        page = await ctx.new_page()
        await page.goto(_resolve_bundle_url("https://en.wikipedia.org/"))
        browser = await p.firefox.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1920, "height": 1080})
        page = await ctx.new_page()
        await page.goto(_resolve_bundle_url("https://en.wikipedia.org/"))
        browser = await p.webkit.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1920, "height": 1080})
        page = await ctx.new_page()
        await page.goto(_resolve_bundle_url("https://en.wikipedia.org/"))
        await page.wait_for_selector('input[name="search"]')
        await page.wait_for_selector('input[name="search"]')
        await page.wait_for_selector('input[name="search"]')
        try:
            await page.get_by_role("player").fill("Playwright (software)")
        except Exception:
            await page.fill('input[name="search"]', "Playwright (software)")
        try:
            await page.get_by_role("player").fill("Playwright (software)")
        except Exception:
            await page.fill('input[name="search"]', "Playwright (software)")
        try:
            await page.get_by_role("player").fill("Playwright (software)")
        except Exception:
            await page.fill('input[name="search"]', "Playwright (software)")
        await page.keyboard.press("Enter")
        await page.keyboard.press("Enter")
        await page.keyboard.press("Enter")
        await page.wait_for_selector("h1#firstHeading")
        await page.wait_for_selector("h1#firstHeading")
        await page.wait_for_selector("h1#firstHeading")
        await page.evaluate("window.scrollBy(0, 600); window.scrollY")
        await page.evaluate("window.scrollBy(0, 600); window.scrollY")
        await page.evaluate("window.scrollBy(0, 600); window.scrollY")
        await page.evaluate("window.scrollBy(0, 600); window.scrollY")
        await page.evaluate("window.scrollBy(0, 600); window.scrollY")
        await page.evaluate("window.scrollBy(0, 600); window.scrollY")
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
