// Auto-generated by octowright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  browser = await chromium.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("https://en.wikipedia.org/"));
  browser = await firefox.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("https://en.wikipedia.org/"));
  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("https://en.wikipedia.org/"));
  await page.waitForSelector("input[name=\"search\"]");
  await page.waitForSelector("input[name=\"search\"]");
  await page.waitForSelector("input[name=\"search\"]");
  try {
    await page.getByRole("player").fill("Playwright (software)");
  } catch {
    await page.fill("input[name=\"search\"]", "Playwright (software)");
  }
  try {
    await page.getByRole("player").fill("Playwright (software)");
  } catch {
    await page.fill("input[name=\"search\"]", "Playwright (software)");
  }
  try {
    await page.getByRole("player").fill("Playwright (software)");
  } catch {
    await page.fill("input[name=\"search\"]", "Playwright (software)");
  }
  await page.keyboard.press("Enter");
  await page.keyboard.press("Enter");
  await page.keyboard.press("Enter");
  await page.waitForSelector("h1#firstHeading");
  await page.waitForSelector("h1#firstHeading");
  await page.waitForSelector("h1#firstHeading");
  await page.evaluate("window.scrollBy(0, 600); window.scrollY");
  await page.evaluate("window.scrollBy(0, 600); window.scrollY");
  await page.evaluate("window.scrollBy(0, 600); window.scrollY");
  await page.evaluate("window.scrollBy(0, 600); window.scrollY");
  await page.evaluate("window.scrollBy(0, 600); window.scrollY");
  await page.evaluate("window.scrollBy(0, 600); window.scrollY");
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
