// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  ctx = await webkit.launchPersistentContext("/Users/tim/.config/octowright/profiles/solo-player/webkit", {
    headless: false,
    viewport: { width: 1280, height: 800 },
  });
  page = ctx.pages()[0] ?? await ctx.newPage();
  await page.goto("file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/macro-replay-loop/seed/login-card.html?persona=solo-player&role=player&kind=webkit&slot=0");
  try {
    await page.getByRole("player", { name: "Email" }).fill("demo@example.com");
  } catch {
    await page.fill("#email", "demo@example.com");
  }
  try {
    await page.getByRole("player", { name: "Password" }).fill("swordfish");
  } catch {
    await page.fill("#password", "swordfish");
  }
  try {
    await page.getByRole("player", { name: "Log in" }).click();
  } catch {
    await page.click("#submit");
  }
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
