# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""Auto-generated by mcp-multi-playwright. Replays a recorded MCP session."""

import asyncio
from pathlib import Path

from playwright.async_api import async_playwright


def _resolve_bundle_url(raw: str) -> str:
    if raw.startswith("bundle://"):
        relative = raw.removeprefix("bundle://")
        return (Path(__file__).resolve().parents[1] / relative).resolve().as_uri()
    return raw


async def main() -> None:
    async with async_playwright() as p:
        browser = await p.webkit.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1920, "height": 1080})
        page = await ctx.new_page()
        await page.goto(
            _resolve_bundle_url("bundle://seed/login-card.html?persona=solo-player&role=player&kind=webkit&slot=0")
        )
        try:
            await page.get_by_role("player", name="Email").fill("demo@example.com")
        except Exception:
            await page.fill("#email", "demo@example.com")
        try:
            await page.get_by_role("player", name="Password").fill("swordfish")
        except Exception:
            await page.fill("#password", "swordfish")
        try:
            await page.get_by_role("player", name="Log in").click()
        except Exception:
            await page.click("#submit")
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
