// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  ctx = await webkit.launchPersistentContext("/Users/tim/.config/octowright/profiles/vs-counter/webkit", {
    headless: false,
    viewport: { width: 1280, height: 800 },
  });
  page = ctx.pages()[0] ?? await ctx.newPage();
  await page.goto("file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/verify-suite/seed/verify-stage.html?persona=vs-counter&role=counter&kind=webkit&slot=1");
  ctx = await webkit.launchPersistentContext("/Users/tim/.config/octowright/profiles/vs-form/webkit", {
    headless: false,
    viewport: { width: 1280, height: 800 },
  });
  page = ctx.pages()[0] ?? await ctx.newPage();
  await page.goto("file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/verify-suite/seed/verify-stage.html?persona=vs-form&role=form&kind=webkit&slot=0");
  ctx = await webkit.launchPersistentContext("/Users/tim/.config/octowright/profiles/vs-arithmetic/webkit", {
    headless: false,
    viewport: { width: 1280, height: 800 },
  });
  page = ctx.pages()[0] ?? await ctx.newPage();
  await page.goto("file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/verify-suite/seed/verify-stage.html?persona=vs-arithmetic&role=arithmetic&kind=webkit&slot=2");
  await page.evaluate("document.body.innerHTML = '<input id=user><input id=pass type=password>'");
  try {
    await page.getByRole("form", { name: "" }).fill("alice");
  } catch {
    await page.fill("#user", "alice");
  }
  try {
    await page.getByRole("form", { name: "" }).fill("hunter2");
  } catch {
    await page.fill("#pass", "hunter2");
  }
  await page.evaluate("(() => { document.body.innerHTML = ''; const b = document.createElement('button'); b.id = 'btn'; b.textContent = 'click'; b.dataset.n = '0'; b.addEventListener('click', () => { b.dataset.n = String(parseInt(b.dataset.n) + 1); }); document.body.appendChild(b); })()");
  try {
    await page.getByRole("counter", { name: "click" }).click();
  } catch {
    await page.click("#btn");
  }
  try {
    await page.getByRole("counter", { name: "click" }).click();
  } catch {
    await page.click("#btn");
  }
  try {
    await page.getByRole("counter", { name: "click" }).click();
  } catch {
    await page.click("#btn");
  }
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
