// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  browser = await chromium.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("https://en.wikipedia.org/wiki/Playwright_(software)"));
  browser = await chromium.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("https://en.wikipedia.org/wiki/Playwright_(software)"));
  await page.waitForSelector("h1#firstHeading");
  await page.getByRole("recorder", { name: "History", exact: true }).click();
  await page.waitForLoadState('networkidle');
  await page.getByRole("recorder", { name: "References", exact: true }).click();
  await page.waitForLoadState('networkidle');
  await page.waitForSelector("h1#firstHeading");
  await page.getByRole("replayer", { name: "History", exact: true }).click();
  await page.waitForLoadState('networkidle');
  await page.getByRole("replayer", { name: "References", exact: true }).click();
  await page.waitForLoadState('networkidle');
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
