# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""Auto-generated by mcp-multi-playwright. Replays a recorded MCP session."""

import asyncio

from playwright.async_api import async_playwright


async def main() -> None:
    async with async_playwright() as p:
        ctx = await p.webkit.launch_persistent_context(
            "/Users/tim/.config/octowright/profiles/solo-player/webkit",
            headless=False,
            viewport={"width": 1280, "height": 800},
        )
        browser = None
        page = ctx.pages[0] if ctx.pages else await ctx.new_page()
        await page.goto(
            "file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/macro-replay-loop/seed/login-card.html"
        )
        await page.evaluate(
            "document.body.innerHTML = '<form><input name=email id=email><input name=password type=password id=password><button id=submit type=button>Log in</button></form>'"
        )
        try:
            await page.get_by_role("player", name="").fill("demo@example.com")
        except Exception:
            await page.fill("#email", "demo@example.com")
        try:
            await page.get_by_role("player", name="").fill("swordfish")
        except Exception:
            await page.fill("#password", "swordfish")
        try:
            await page.get_by_role("player", name="Log in").click()
        except Exception:
            await page.click("#submit")
        await page.keyboard.press("Escape")
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
