# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""Auto-generated by mcp-multi-playwright. Replays a recorded MCP session."""

import asyncio
from pathlib import Path

from playwright.async_api import async_playwright


def _resolve_bundle_url(raw: str) -> str:
    if raw.startswith("bundle://"):
        relative = raw.removeprefix("bundle://")
        return (Path(__file__).resolve().parents[1] / relative).resolve().as_uri()
    return raw


async def main() -> None:
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1920, "height": 1080})
        page = await ctx.new_page()
        await page.goto(_resolve_bundle_url("https://en.wikipedia.org/wiki/Playwright_(software)"))
        browser = await p.chromium.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1920, "height": 1080})
        page = await ctx.new_page()
        await page.goto(_resolve_bundle_url("https://en.wikipedia.org/wiki/Playwright_(software)"))
        await page.wait_for_selector("h1#firstHeading")
        await page.get_by_role("recorder", name="History", exact=True).click()
        await page.wait_for_load_state("networkidle")
        await page.get_by_role("recorder", name="References", exact=True).click()
        await page.wait_for_load_state("networkidle")
        await page.wait_for_selector("h1#firstHeading")
        await page.get_by_role("replayer", name="History", exact=True).click()
        await page.wait_for_load_state("networkidle")
        await page.get_by_role("replayer", name="References", exact=True).click()
        await page.wait_for_load_state("networkidle")
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
