// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/login-card.html?persona=solo-player&role=player&kind=webkit&slot=0"));
  try {
    await page.getByRole("player", { name: "Email" }).fill("demo@example.com");
  } catch {
    await page.fill("#email", "demo@example.com");
  }
  try {
    await page.getByRole("player", { name: "Password" }).fill("swordfish");
  } catch {
    await page.fill("#password", "swordfish");
  }
  try {
    await page.getByRole("player", { name: "Log in" }).click();
  } catch {
    await page.click("#submit");
  }
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
