// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  browser = await webkit.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("bundle://seed/welcome.html?persona=solo-player&role=player&kind=webkit&slot=0"));
  await page.evaluate("document.body.innerHTML = '<form><input id=user name=user><input id=pass type=password name=pass><button id=submit type=button>Go</button></form>'");
  await page.evaluate("document.body.innerHTML = '<h1 id=title>Demo</h1><p class=note>hi</p>'");
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
