// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  ctx = await webkit.launchPersistentContext("/Users/tim/.config/octowright/profiles/solo-player/webkit", {
    headless: false,
    viewport: { width: 1280, height: 800 },
  });
  page = ctx.pages()[0] ?? await ctx.newPage();
  await page.goto("file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/first-run-session/seed/welcome.html?persona=solo-player&role=player&kind=webkit&slot=0");
  await page.evaluate("document.body.innerHTML = '<form><input id=user name=user><input id=pass type=password name=pass><button id=submit type=button>Go</button></form>'");
  await page.evaluate("document.body.innerHTML = '<h1 id=title>Demo</h1><p class=note>hi</p>'");
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
