# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""MCP server entrypoint.

The shared FastMCP instance and live pools live in ``_state``. Each domain
submodule (`browser`, `personas`, `macros`, `goldens`, `scenarios`) registers
its tools against that shared instance at import time, so importing this
package is enough to make every tool callable.

`registered_tool_names` and `recordings_dir` are re-exported here for
`cli.py selftest` and external introspection.
"""

from __future__ import annotations

# Submodule imports trigger @mcp.tool registration via decorator side effects.
# Order does not matter; F401 ignored intentionally.
from octowright.server import browser as _browser  # noqa: F401
from octowright.server import captures as _captures  # noqa: F401
from octowright.server import goldens as _goldens  # noqa: F401
from octowright.server import macros as _macros  # noqa: F401
from octowright.server import meta as _meta  # noqa: F401
from octowright.server import personas as _personas  # noqa: F401
from octowright.server import scenarios as _scenarios  # noqa: F401
from octowright.server._state import log, mcp, pool, scenario_pool

# Re-export every tool function at the package level for direct test access
# (e.g. `from octowright import server; server.browser_open_trace(...)`).
from octowright.server.browser import (
    browser_brief,
    browser_capture_and_close,
    browser_click,
    browser_click_by,
    browser_close,
    browser_close_all,
    browser_console_messages,
    browser_downloads,
    browser_drag,
    browser_evaluate,
    browser_evaluate_each,
    browser_expect_js,
    browser_expect_selector,
    browser_expect_text,
    browser_expect_url,
    browser_export_script,
    browser_fill,
    browser_fill_by,
    browser_get_text_by,
    browser_hover,
    browser_launch,
    browser_list,
    browser_list_frames,
    browser_mock_route,
    browser_navigate,
    browser_navigate_back,
    browser_navigate_each,
    browser_network_requests,
    browser_open_trace,
    browser_open_url,
    browser_press_key,
    browser_quick_launch,
    browser_read_markdown,
    browser_recording_path,
    browser_relaunch_fluid,
    browser_reset_frame,
    browser_resize,
    browser_resize_each,
    browser_screenshot,
    browser_screenshot_each,
    browser_select_option,
    browser_set_dialog_policy,
    browser_set_input_files,
    browser_snapshot,
    browser_spawn_roster,
    browser_suggest_for_url,
    browser_switch_frame,
    browser_tail_recording,
    browser_type,
    browser_unmock_route,
    browser_viewport_status,
    browser_viewport_sync,
    browser_wait_for,
    browser_wait_for_download,
    browser_wait_for_each,
    page_close,
    page_list,
    page_switch,
)
from octowright.server.captures import (
    capture_cleanup,
    capture_create,
    capture_get,
    capture_list,
    capture_search,
    octowright_storage_report,
)
from octowright.server.goldens import (
    golden_assert,
    golden_delete,
    golden_list,
    golden_save,
    golden_verify_loop,
)
from octowright.server.macros import (
    macro_compile,
    macro_delete,
    macro_explain,
    macro_lint,
    macro_list,
    macro_repair_preview,
    macro_run,
    macro_run_sequence,
    macro_save,
    profile_cleanup,
    recordings_cleanup,
    run_test_suite,
)
from octowright.server.meta import (
    octowright_advisor_record_macro_observation,
    octowright_advisor_set_preference,
    octowright_advisor_status,
    octowright_check_takeover,
    octowright_dashboard_url,
    octowright_status,
)
from octowright.server.personas import (
    persona_create,
    persona_credentials_check,
    persona_delete,
    persona_get,
    persona_list,
    profile_delete,
    profile_list,
)
from octowright.server.registry import recordings_dir, registered_tool_names
from octowright.server.scenarios import (
    scenario_list,
    scenario_participants,
    scenario_plan,
    scenario_remap_participants,
    scenario_run_as_test,
    scenario_run_macro,
    scenario_start,
    scenario_status,
    scenario_stop,
    scenario_tail,
)

__all__ = [
    "browser_brief",
    "browser_capture_and_close",
    "browser_click",
    "browser_click_by",
    "browser_close",
    "browser_close_all",
    "browser_console_messages",
    "browser_downloads",
    "browser_drag",
    "browser_evaluate",
    "browser_evaluate_each",
    "browser_expect_js",
    "browser_expect_selector",
    "browser_expect_text",
    "browser_expect_url",
    "browser_export_script",
    "browser_fill",
    "browser_fill_by",
    "browser_get_text_by",
    "browser_hover",
    "browser_launch",
    "browser_list",
    "browser_list_frames",
    "browser_mock_route",
    "browser_navigate",
    "browser_navigate_back",
    "browser_navigate_each",
    "browser_network_requests",
    "browser_open_trace",
    "browser_open_url",
    "browser_press_key",
    "browser_quick_launch",
    "browser_read_markdown",
    "browser_recording_path",
    "browser_relaunch_fluid",
    "browser_reset_frame",
    "browser_resize",
    "browser_resize_each",
    "browser_screenshot",
    "browser_screenshot_each",
    "browser_select_option",
    "browser_set_dialog_policy",
    "browser_set_input_files",
    "browser_snapshot",
    "browser_spawn_roster",
    "browser_suggest_for_url",
    "browser_switch_frame",
    "browser_tail_recording",
    "browser_type",
    "browser_unmock_route",
    "browser_viewport_status",
    "browser_viewport_sync",
    "browser_wait_for",
    "browser_wait_for_download",
    "browser_wait_for_each",
    "capture_cleanup",
    "capture_create",
    "capture_get",
    "capture_list",
    "capture_search",
    "golden_assert",
    "golden_delete",
    "golden_list",
    "golden_save",
    "golden_verify_loop",
    "log",
    "macro_compile",
    "macro_delete",
    "macro_explain",
    "macro_lint",
    "macro_list",
    "macro_repair_preview",
    "macro_run",
    "macro_run_sequence",
    "macro_save",
    "mcp",
    "octowright_advisor_record_macro_observation",
    "octowright_advisor_set_preference",
    "octowright_advisor_status",
    "octowright_check_takeover",
    "octowright_dashboard_url",
    "octowright_status",
    "octowright_storage_report",
    "page_close",
    "page_list",
    "page_switch",
    "persona_create",
    "persona_credentials_check",
    "persona_delete",
    "persona_get",
    "persona_list",
    "pool",
    "profile_cleanup",
    "profile_delete",
    "profile_list",
    "recordings_cleanup",
    "recordings_dir",
    "registered_tool_names",
    "run_test_suite",
    "scenario_list",
    "scenario_participants",
    "scenario_plan",
    "scenario_pool",
    "scenario_remap_participants",
    "scenario_run_as_test",
    "scenario_run_macro",
    "scenario_start",
    "scenario_status",
    "scenario_stop",
    "scenario_tail",
]
