// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  ctx = await webkit.launchPersistentContext("/Users/tim/.config/octowright/profiles/duo-player/webkit", {
    headless: false,
    viewport: { width: 1280, height: 800 },
  });
  page = ctx.pages()[0] ?? await ctx.newPage();
  await page.goto("file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/role-based-duo/seed/duo-board.html");
  ctx = await webkit.launchPersistentContext("/Users/tim/.config/octowright/profiles/duo-monitor/webkit", {
    headless: false,
    viewport: { width: 1280, height: 800 },
  });
  page = ctx.pages()[0] ?? await ctx.newPage();
  await page.goto("file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/role-based-duo/seed/control-room.html");
  await page.evaluate("document.body.innerHTML = '<h1 id=title>Demo</h1><p class=note>hi</p>'");
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
