// Auto-generated by mcp-multi-playwright. Replays a recorded MCP session.
import { chromium, firefox, webkit, Browser, BrowserContext, Page } from "playwright";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const resolveBundleUrl = (raw: string): string => {
  if (raw.startsWith("bundle://")) {
    return pathToFileURL(path.resolve(here, "..", raw.slice("bundle://".length))).toString();
  }
  return raw;
};

(async () => {
  let browser: Browser | null = null;
  let ctx!: BrowserContext;
  let page!: Page;

  browser = await chromium.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/dashboard.html"));
  browser = await chromium.launch({ headless: true });
  ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
  page = await ctx.newPage();
  await page.goto(resolveBundleUrl("http://127.0.0.1:7900/form-flow.html"));
  await page.waitForSelector("#name");
  try {
    await page.getByRole("player", { name: "Full name" }).fill("Octavia Wright");
  } catch {
    await page.fill("#name", "Octavia Wright");
  }
  try {
    await page.getByRole("player", { name: "Next" }).click();
  } catch {
    await page.click("#next-1");
  }
  await page.waitForSelector(".step--active #email");
  try {
    await page.getByRole("player", { name: "Email" }).fill("octavia@example.com");
  } catch {
    await page.fill("#email", "octavia@example.com");
  }
  try {
    await page.getByRole("player", { name: "Next" }).click();
  } catch {
    await page.click("#next-2");
  }
  await page.waitForSelector(".step--active #notes");
  try {
    await page.getByRole("player", { name: "Notes" }).fill("Demo run \u2014 replay this to see the dashboard fill again.");
  } catch {
    await page.fill("#notes", "Demo run \u2014 replay this to see the dashboard fill again.");
  }
  try {
    await page.getByRole("player", { name: "Submit" }).click();
  } catch {
    await page.click("#submit");
  }
  await page.waitForLoadState('networkidle');
  if (browser !== null) {
    await browser.close();
  } else {
    await ctx.close();
  }
})();
