# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""Auto-generated by octowright. Replays a recorded MCP session."""

import asyncio
from pathlib import Path

from playwright.async_api import async_playwright


def _resolve_bundle_url(raw: str) -> str:
    if raw.startswith("bundle://"):
        relative = raw.removeprefix("bundle://")
        return (Path(__file__).resolve().parents[1] / relative).resolve().as_uri()
    return raw


async def main() -> None:
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        ctx = await browser.new_context(viewport={"width": 1920, "height": 1080})
        page = await ctx.new_page()
        await page.goto(_resolve_bundle_url("http://127.0.0.1:7900/form-flow.html"))
        browser = await p.chromium.launch(headless=False)
        ctx = await browser.new_context(viewport={"width": 1920, "height": 1080})
        page = await ctx.new_page()
        await page.goto(_resolve_bundle_url("http://127.0.0.1:7900/dashboard.html"))
        await page.wait_for_selector("#name")
        try:
            await page.get_by_role("player", name="Full name").fill("Octavia Wright")
        except Exception:
            await page.fill("#name", "Octavia Wright")
        try:
            await page.get_by_role("player", name="Next").click()
        except Exception:
            await page.click("#next-1")
        await page.wait_for_selector(".step--active #email")
        try:
            await page.get_by_role("player", name="Email").fill("octavia@octowright.test")
        except Exception:
            await page.fill("#email", "octavia@octowright.test")
        try:
            await page.get_by_role("player", name="Next").click()
        except Exception:
            await page.click("#next-2")
        await page.wait_for_selector(".step--active #notes")
        try:
            await page.get_by_role("player", name="Notes").fill(
                "Demo run — replay this to see the dashboard fill again."
            )
        except Exception:
            await page.fill("#notes", "Demo run — replay this to see the dashboard fill again.")
        try:
            await page.get_by_role("player", name="Submit").click()
        except Exception:
            await page.click("#submit")
        if "submitted" not in await page.locator("#status").inner_text():
            raise RuntimeError("Text mismatch")
        await page.wait_for_load_state("networkidle")
        if not await page.evaluate("document.querySelectorAll('#rows tr:not(.empty)').length >= 3"):
            raise RuntimeError("JS mismatch")
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
