# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""Auto-generated by mcp-multi-playwright. Replays a recorded MCP session."""

import asyncio
from pathlib import Path

from playwright.async_api import async_playwright


def _resolve_bundle_url(raw: str) -> str:
    if raw.startswith("bundle://"):
        relative = raw.removeprefix("bundle://")
        return (Path(__file__).resolve().parents[1] / relative).resolve().as_uri()
    return raw


async def main() -> None:
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(
            _resolve_bundle_url("bundle://seed/orchestration-stage.html?persona=p7&role=player&kind=chromium&slot=6")
        )
        browser = await p.chromium.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(
            _resolve_bundle_url("bundle://seed/orchestration-stage.html?persona=p6&role=player&kind=chromium&slot=5")
        )
        browser = await p.webkit.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(
            _resolve_bundle_url("bundle://seed/orchestration-stage.html?persona=p3&role=player&kind=webkit&slot=2")
        )
        browser = await p.webkit.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(
            _resolve_bundle_url("bundle://seed/orchestration-stage.html?persona=p1&role=player&kind=webkit&slot=0")
        )
        browser = await p.webkit.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(
            _resolve_bundle_url("bundle://seed/orchestration-stage.html?persona=p2&role=player&kind=webkit&slot=1")
        )
        browser = await p.webkit.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(
            _resolve_bundle_url(
                "bundle://seed/orchestration-stage.html?persona=spectator&role=main-site&kind=webkit&slot=8"
            )
        )
        browser = await p.webkit.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(
            _resolve_bundle_url("bundle://seed/orchestration-stage.html?persona=ops&role=monitor&kind=webkit&slot=7")
        )
        browser = await p.firefox.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(
            _resolve_bundle_url("bundle://seed/orchestration-stage.html?persona=p4&role=player&kind=firefox&slot=3")
        )
        browser = await p.firefox.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(
            _resolve_bundle_url("bundle://seed/orchestration-stage.html?persona=p5&role=player&kind=firefox&slot=4")
        )
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
