# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""Auto-generated by mcp-multi-playwright. Replays a recorded MCP session."""

import asyncio

from playwright.async_api import async_playwright


async def main() -> None:
    async with async_playwright() as p:
        ctx = await p.webkit.launch_persistent_context(
            "/Users/tim/.config/octowright/profiles/fix-b/webkit",
            headless=False,
            viewport={"width": 1280, "height": 800},
        )
        browser = None
        page = ctx.pages[0] if ctx.pages else await ctx.new_page()
        await page.goto(
            "file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/fixture-lab/seed/fixtures.html?persona=fix-b&role=player&kind=webkit&slot=1"
        )
        ctx = await p.webkit.launch_persistent_context(
            "/Users/tim/.config/octowright/profiles/fix-a/webkit",
            headless=False,
            viewport={"width": 1280, "height": 800},
        )
        browser = None
        page = ctx.pages[0] if ctx.pages else await ctx.new_page()
        await page.goto(
            "file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/fixture-lab/seed/fixtures.html?persona=fix-a&role=player&kind=webkit&slot=0"
        )
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
