# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""Auto-generated by mcp-multi-playwright. Replays a recorded MCP session."""

import asyncio
from pathlib import Path

from playwright.async_api import async_playwright


def _resolve_bundle_url(raw: str) -> str:
    if raw.startswith("bundle://"):
        relative = raw.removeprefix("bundle://")
        return (Path(__file__).resolve().parents[1] / relative).resolve().as_uri()
    return raw


async def main() -> None:
    async with async_playwright() as p:
        browser = await p.webkit.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(_resolve_bundle_url("bundle://seed/fixtures.html?persona=fix-b&role=player&kind=webkit&slot=1"))
        browser = await p.webkit.launch(headless=True)
        ctx = await browser.new_context(viewport={"width": 1280, "height": 800})
        page = await ctx.new_page()
        await page.goto(_resolve_bundle_url("bundle://seed/fixtures.html?persona=fix-a&role=player&kind=webkit&slot=0"))
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
