# SPDX-FileCopyrightText: Copyright (C) 2026 provide.io llc
# SPDX-License-Identifier: Apache-2.0
# SPDX-Comment: Part of octowright.
#

"""Auto-generated by mcp-multi-playwright. Replays a recorded MCP session."""

import asyncio

from playwright.async_api import async_playwright


async def main() -> None:
    async with async_playwright() as p:
        ctx = await p.webkit.launch_persistent_context(
            "/Users/tim/.config/octowright/profiles/cx-webkit/webkit",
            headless=False,
            viewport={"width": 1280, "height": 800},
        )
        browser = None
        page = ctx.pages[0] if ctx.pages else await ctx.new_page()
        await page.goto(
            "file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/cross-engine-trio/seed/trio-board.html?persona=cx-webkit&role=player&kind=webkit&slot=2"
        )
        ctx = await p.firefox.launch_persistent_context(
            "/Users/tim/.config/octowright/profiles/cx-firefox/firefox",
            headless=False,
            viewport={"width": 1280, "height": 800},
        )
        browser = None
        page = ctx.pages[0] if ctx.pages else await ctx.new_page()
        await page.goto(
            "file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/cross-engine-trio/seed/trio-board.html?persona=cx-firefox&role=player&kind=firefox&slot=1"
        )
        ctx = await p.chromium.launch_persistent_context(
            "/Users/tim/.config/octowright/profiles/cx-chromium/chromium",
            headless=False,
            viewport={"width": 1280, "height": 800},
        )
        browser = None
        page = ctx.pages[0] if ctx.pages else await ctx.new_page()
        await page.goto(
            "file:///Users/tim/code/gh/provide-io/octowright/demo/bundles/cross-engine-trio/seed/trio-board.html?persona=cx-chromium&role=player&kind=chromium&slot=0"
        )
        if browser is not None:
            await browser.close()
        else:
            await ctx.close()


if __name__ == "__main__":
    asyncio.run(main())
